### ISSUE TITLE
As a Grant Recipient I'd like some context about what it means to "Submit Milestone", and have some way to communicate milestone progress on the milestone as I submit it

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#126]
When I clicked this button I expected something to pop up either asking me to supply some info about the milestone, or giving me some info (could be some context next to the button, or in a popup) about what it means to submit a milestone. 

Instead, it immediately asks me to approve a transaction on click. 

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/77bd3d70-4e3f-4d48-b79f-e48abffb8ddd)

**Comment by jordanlesich** [comment]
Steps: 
- [ ] See where we might be able to store this state (if possible) 
- [ ] If possible, add to transaction data. 
- [ ] index
- [ ] Add to UI
